module.exports = {
  GET_STARTED: "GET_STARTED",
  SEARCH_COURSES: "SEARCH_COURSES",
  VIEW_CATEGORIES: "VIEW_CATEGORIES",
  VIEW_SUB_CATEGORIES: "SUB_CATEGORIES",
  VIEW_COURSES_CAT: 'COURSES_CAT',
  VIEW_DETAIL_COURSE: "VIEW_DETAIL_COURSE",
  RESTART_BOT: "RESTART_BOT",
  DETAIL_COURSE: "DETAIL_COURSE",
};
